### ISSUE TITLE
Window resize for controller inputs

### ISSUE THREAD

**Issue by mhamz-iit** [Waterdish/Shipwright-Android#8]
The window to map the controllers has a fixed size. I'm playing in an RG405M device, whch has a 4:3 screen, so not super wide. I cannot remap the right stick since the window does not cover it.

The "additional controller options" window is indeed resizeable, so it may be simple to implement this.

I have yet to see if I can modify some other configuration file in my PC to map the right stick, that may be a work around.

**Comment by Waterdish** [comment]
I'll see if I can make it resizable. In the meantime, you're probably right that you can use a file from the pc.

**Comment by mhamz-iit** [comment]
shipofharkanian.json has the controller mappings. It's all coded in numbers though, so I'm not sure what mappings are what. I'm guessing it's in Slot_0, and the last 4 values corresponding to the c-buttons. Those are 6,7,8 and 9. I don't know what corresponding values to put to assign the d-pad, so I can leave the right stick unassigned. Again, just guesses.

**Comment by foxhound311** [comment]
![Screenshot_20231023-224143](https://github.com/Waterdish/Shipwright-Android/assets/51274764/f84e75c8-4af7-49d3-ab59-f638b617ed94)


This is what it looks like on a Retroid pocket 3+

**Comment by foxhound311** [comment]
> shipofharkanian.json has the controller mappings. It's all coded in numbers though, so I'm not sure what mappings are what. I'm guessing it's in Slot_0, and the last 4 values corresponding to the c-buttons. Those are 6,7,8 and 9. I don't know what corresponding values to put to assign the d-pad, so I can leave the right stick unassigned. Again, just guesses.

I mapped them by reinstalling first release, remapping them there and going back to latest.

**Comment by mhamz-iit** [comment]
Would you mind posting the relevant part of your json file? I assume you mapped the right stick for free camera, right?

I think this is the relevant part in the json (for Slot_0):
"Mappings": {
                    "-512": 65536,
                    "-513": 524288,
                    "-514": 2,
                    "-515": 8,
                    "-516": 0,
                    "-517": 0,
                    "0": 32768,
                    "1": 32768,
                    "10": 16,
                    "11": 2048,
                    "12": 1024,
                    "13": 512,
                    "14": 256,
                    "3": 16384,
                    "512": 131072,
                    "513": 262144,
                    "514": 1,
                    "515": 4,
                    "516": 32,
                    "517": 64,
                    "6": 4096,
                    "7": 64,
                    "8": 128,
                    "9": 8192
                },

**Comment by foxhound311** [comment]
> Would you mind posting the relevant part of your json file? I assume you mapped the right stick for free camera, right?
> 
> I think this is the relevant part in the json (for Slot_0): "Mappings": { "-512": 65536, "-513": 524288, "-514": 2, "-515": 8, "-516": 0, "-517": 0, "0": 32768, "1": 32768, "10": 16, "11": 2048, "12": 1024, "13": 512, "14": 256, "3": 16384, "512": 131072, "513": 262144, "514": 1, "515": 4, "516": 32, "517": 64, "6": 4096, "7": 64, "8": 128, "9": 8192 },

I’m at work but I have the file online…
https://mega.nz/file/CiBxWJhD#JDnDA7cwvgfCFnox1aa6KvsD-Tg_dQYzE8Z2IAhrPDk

**Comment by mhamz-iit** [comment]
Thank you! I appreciate it.

**Comment by Waterdish** [comment]
I added a new version of the app in 1.0.2 that changes the UI back to the small size if you have a device that needs it.

**Comment by mhamz-iit** [comment]
That's awesome! It didn't work in my case though, I reinstalled the apk and just transferred my old .otr files, but the sizing is the windows is the same. Unless there is a setting I'm missing?

Also (this could be a separate issue), I start the game in MQ mode (with both .otr files for vanilla and MQ) but the game is vanilla. This happened with the 1.0.1 and 1.0.2.

**Comment by Waterdish** [comment]
New update should fix these issues.

**Comment by foxhound311** [comment]
> New update should fix these issues.

Thank you, that is awesome.

**Comment by mhamz-iit** [comment]
This is great, MQ issue is resolved. The new window sizes are useful, I can remap the right stick now. 

However, it's still impossible to see the c-stick controller mappings on a 4:3 screen (window ends in the right stick with smallest font size). It is playable using the dpad option, so not as big of a deal as before. Either a resizable or a scrolling window would be the fix.

**Comment by mhamz-iit** [comment]
Yes, I did that, I resized using the smallest value, but it's still not enough to see the c-button section.

**Comment by Waterdish** [comment]
Fixed in latest update
